language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.18.x
  - 1.19.x

go_import_path: github.com/chensanle/sliset

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -s https://codecov.io/bash >
    .codecov && chmod +x .codecov && ./.codecov; else bash <(curl -s https://codecov.io/bash);
    fi

env:
  global:
    - GO111MODULE=on