name: golang-ci

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  golangci:
    name: "Golang ${{ matrix.go-version }} ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.18']
        os: ['ubuntu-latest']
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout Go code
        uses: actions/checkout@v2
      
      - name: Set op Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...
      
      - name: Test
        run: go test -v ./...

